name: Playwright Tests
on:
  push:
    branches: [ playwright-tests ]
#  pull_request:
#    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: playwright-tests
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: "Docker for web"
      run: docker build . -t telemetrybalkan/orb
      env:
        HOME: /web
    - name: "Docker for ros"
      run: docker build . -t telemetrybalkan/ros
      env:
          HOME: /docker
    - name: "Docker compose"
      run: docker compose up -d
      env:
        HOME: /docker
    - name: Install dependencies
      run: npm ci
      env:
        HOME: /playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      env:
        HOME: /playwright
    - name: Run Playwright tests
      run: npx playwright test
      env:
        HOME: /playwright
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
