name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "45 14 * * *"
  push:
    branches: [ playwright-tests ]
#  pull_request:
#    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: playwright-tests
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: "Docker for web"
      run: docker build . -t telemetrybalkan/orb
      working-directory: ./web
    - name: "Docker for ros"
      run: docker build . -t telemetrybalkan/ros
      working-directory: ./docker
    - name: "Docker compose"
      run: docker compose up -d
      working-directory: ./docker
    - name: Install dependencies
      run: npm ci
      working-directory: ./playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./playwright
    - run: |
        sudo apt-get install default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
        sudo dpkg -i allure_2.18.1-1_all.deb
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./playwright
    - name: Install the Allure Playwright
      if: always()
      run: npm install --save-dev allure-playwright
      working-directory: ./playwright
    - name: Generate the Allure Report
      if: always()
      run: allure generate allure-results -o allure-report
      working-directory: ./playwright
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./playwright/playwright-report/
        retention-days: 20
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-results
        path: ./playwright/allure-results
        retention-days: 20

#    - name: Get Allure history
#      uses: actions/checkout@v3
#      if: always()
#      continue-on-error: true
#      with:
#        ref: gh-pages
#        path: gh-pages
#
#    - uses: simple-elf/allure-report-action@master
#      if: always()
#      id: allure-report
#      with:
#        allure_results: allure-results
##        gh_pages: gh-pages
#        allure_report: allure-report
#        allure_history: allure-history
#        keep_reports: 20

#    - name: Deploy report to Github Pages
#      if: always()
#      uses: peaceiris/actions-gh-pages@v3
#      env:
#        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: allure-history
#  send_report:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        ref: playwright-tests
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      if: always()
      with:
        distribution: 'temurin'
        java-version: 8
    - name: "Send message"
      if: always()
      run: java "-DconfigFile=notifications/config.json" -jar notifications/allure-notifications-4.2.1.jar
      working-directory: ./playwright
